apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aksservice.type }}
  ports:
    - port: {{ .Values.aksservice.port }}
      #targetPort: {{ .Values.aksservice.targetPort }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
