apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello
  namespace: default
spec:
  dnsNames:
    - {{ .Values.dnsName }}
  secretName: {{ .Values.secretName }}
  issuerRef:
    name: {{ .Values.certIssuer.name }}
    kind: ClusterIssuer